Replace `pkg_resources` with `importlib.metadata` and bump minimal Python version to 3.8
FEniCS/ufl pull request #158
Opened 2023-04-24 14:14 UTC by jorgensd

- Fix #157
- Fix integration tests (TSFC and DOLFINx/FFCx)

2023-04-24 14:29 UTC, jorgensd commented
This PR also fixes the TSFC and DOLFINx integration tests

2023-04-24 16:44 UTC, garth-wells requested changes

2023-04-24 16:44 UTC, garth-wells commented on .github/workflows/fenicsx-tests.yml
> +      CC: gcc
The `CC` and `CXX` lines can be removed.

2023-04-24 16:44 UTC, garth-wells commented on doc/sphinx/source/conf.py
> +# import sys
Remove commented lines.

2023-04-24 16:44 UTC, garth-wells commented on setup.cfg
>      Programming Language :: Python :: 3.10
Add 3.11 to list of versions?

2023-04-24 17:13 UTC, jorgensd commented on .github/workflows/fenicsx-tests.yml
> +      CXX: g++
```suggestion
```

2023-04-24 17:13 UTC, jorgensd commented on doc/sphinx/source/conf.py
> +# import os
```suggestion
```

2023-04-24 17:14 UTC, jorgensd commented on setup.cfg
>      Programming Language :: Python :: 3.10
```suggestion
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
```

2023-04-24 17:14 UTC, jorgensd commented on .github/workflows/pythonapp.yml
> +        python-version: ['3.8', '3.9', '3.10', "3.11"]
```suggestion
        python-version: ['3.8', '3.9', '3.10', '3.11']
```

2023-04-25 07:26 UTC, garth-wells approved these changes

2023-04-25 08:24 UTC, merged