Delete unused code
FEniCS/ufl pull request #163
Opened 2023-05-23 15:35 UTC by mscroggs

Working though the functions that vulture suggests are unused.

Opening the PR as a draft to run tests on CI.

2023-06-02 08:54 UTC, garth-wells commented
@mscroggs tests look green - is this ready to go?

2023-06-02 14:11 UTC, mscroggs commented
> @mscroggs tests look green - is this ready to go?

I think there's still more that can be deleted, so was still planning to add more to this PR. I'm on holiday this week, but will continue on Monday

2023-06-02 14:21 UTC, dham requested changes

2023-06-02 14:21 UTC, dham commented on ufl/formatting/ufl2unicode.py
ufl2unicode is used by Firedrake-adjoint to generate visualisations of the tape. It's also used by legacy dolfin-adjoint for the same purpose and any future FEniCSx-adjoint would presumably want the same.

2023-06-06 11:56 UTC, mscroggs commented on ufl/formatting/ufl2unicode.py
I've readded ufl2unicode

2023-06-07 08:13 UTC, dham commented
see: https://github.com/firedrakeproject/firedrake/pull/2972

2023-06-07 10:51 UTC, mscroggs commented
Converted to draft while I fix the failing Firedrake tests

2023-07-12 08:48 UTC, garth-wells approved these changes

2023-07-13 09:34 UTC, merged