Add degree argument to tensor product element reconstruction
FEniCS/ufl pull request #46
Opened 2021-01-25 19:42 UTC by rckirby

In using low-order preconditioners, we need to reconstruct a finite element with a lower-degree instance of the same element family.  This PR enables this for tensor product elements.

2021-02-13 12:13 UTC, wence- requested changes

2021-02-13 12:13 UTC, wence- commented on ufl/finiteelement/tensorproductelement.py
> +                                                        subel.cell(),
Ignores the provided cell argument

2021-02-13 12:13 UTC, wence- commented on ufl/finiteelement/tensorproductelement.py
> +                                                        subel.cell(),
Likewise here

2021-02-13 12:13 UTC, wence- commented on ufl/finiteelement/tensorproductelement.py
Should probably check that the lengths match

2021-02-15 20:20 UTC, rckirby commented
Pablo's [PMGSNES PR](https://github.com/firedrakeproject/firedrake/pull/1963) over on Firedrake does a lot of what I need here, and it makes sense to work in one place at a time.  His is more general, and we should try to migrate that over here once it lands.  So I'm converting this to draft for the time being.

2023-09-12 08:10 UTC, closed without merging